# mkdocs.yml
site_name: Din치mica Molecular

  
theme:
  name: "material"

plugins:
  - mkdocstrings


nav:
  - Introducci칩n: index.md
  - Tutorial: tutorial.md
  - An치lisis de datos: analisis_datos.md
  - Documentaci칩n: documentation.md
  
