# mkdocs.yml
site_name: Dinámica Molecular

  
theme:
  name: "material"

plugins:
  - mkdocstrings


nav:
  - Introducción: index.md
  - Análisis de datos: analisis_datos.md
  - Documentación de Clases: classes.md
  - Documentación del Main: main.md
  
