# mkdocs.yml
site_name: Dinámica Molecular

  
theme:
  name: "material"

plugins:
  - mkdocstrings


nav:
  - Introducción: index.md
  - Análisis de datos: analisis_datos.md
  - Documentación de Clases: classes.md
  - Documentación para varios discos: main.md
  - Documentación para 4 discos: four_disk.md
  - Resultados: resultados.md
